### ISSUE TITLE
Break #issue29 : frontend ->add a button can let the user update historic grade.

### ISSUE THREAD

**Issue by zihaoxu20010109** [ucsb-cs156-s23/proj-courses-s23-7pm-3#10]
As a...
admin

I can...
upload historic grad information

So that...
it can be displayed to users that upload successfully.

#fontend:
- [ ] add a button in the admin/jobs where an admin can upload the data by the GET endpoint in the Gradehistory controller.

**Comment by wq12li** [comment]
Canceled.
