### ISSUE TITLE
Fix stryker code in frontend

### ISSUE THREAD

**Issue by khtran1** [ucsb-cs156-s23/proj-courses-s23-7pm-3#40]
See [this Slack post by Professor Conrad](https://ucsb-cs156-s23.slack.com/archives/C050779M19P/p1685726928710669).

- [ ] Change all occurrences of `// Stryker enable all` to `// Stryker restore all`
- [ ] Ensure mutation testing still passes, as before we might have had some mutation tests not happening.

**Comment by wq12li** [comment]
Canceled.
